# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: '2.1'
orbs:
  aws-s3: circleci/aws-s3@3.0
jobs:
  test:
    docker:
      - image: 'cimg/node:17.8.0-browsers'
    steps:
      - checkout
      - run: npm install && npm test
  deploy:
    docker:
      - image: 'cimg/node:17.8.0-browsers'
    steps:
      - checkout
      - run: mkdir bucket && echo "lorem ipsum" > bucket/build_asset.txt
      - aws-s3/sync:
          arguments: |
            --acl public-read \
            --cache-control "max-age=86400"
          from: bucket
          to: 's3://ci-cd-jjimenez'
workflows:
  test_build_deploy:
    jobs:
      - test
      - deploy:
         requires:
          - test

