# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: '2.1'
orbs:
  node: circleci/node@x.y
jobs:
  test:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - checkout
      - node/install:
          node-version: '16.14.2'
      - run: npm install && npm test
workflows:
  test_and_build:
    jobs:
      - test

